[package]
name = "griffin-dalby/carrot"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

include = [
    "wally.toml",
    "src/*"
]

exclude = [
    "Build/*",
    "DevPackages/*",
    "tests/*",

    "**/*.spec.luau",
    "**/__tests__/",
    "**.json",
]

[dev-dependencies]
Jest = "jsdotlua/jest@3.10.0"
JestGlobals = "jsdotlua/jest-globals@3.10.0"

[dependencies]
